### ISSUE TITLE
`get_unit_cost` and zerg buildings

### ISSUE THREAD

**Issue by vanderlokken** [UltraMachine/rust-sc2#11]
The `Bot::get_unit_cost` method returns uncorrected values for zerg buildings, which include additional 50 minerals (the cost of a drone). For `UnitTypeId::SpawningPool` the returned value is 250. Since the aforementioned method is used to implement `Bot::subtract_resources` I'd suggest fixing this behaviour. It's counter-intuitive that `Bot::subtract_resources(UnitTypeId::SpawningPool)` subtracts 250 minerals, and the real mineral counter and the `bot.minerals` counter become out of sync for the rest of a step.

**Comment by UltraMachine** [comment]
Should be fixed now in e1187ea.

**Comment by vanderlokken** [comment]
Thank you. Can confirm: now it works as intended.
