### ISSUE TITLE
`get_enemy_expansion` returns the enemy starting location

### ISSUE THREAD

**Issue by vanderlokken** [UltraMachine/rust-sc2#13]
The `Bot::get_enemy_expansion` method returns the enemy starting location (unless you've revealed the enemy "townhall" before, I suppose). In its current form this method is pretty meaningless. I suggest fixing it like this:

```
self.units.enemy.townhalls.iter().all(|t| t.is_further(7.0, *loc))
    && self.enemy_start.is_further(7.0, *loc))
```

**Comment by UltraMachine** [comment]
Fixed in fdedea0.
