### ISSUE TITLE
race_values seems to be unset

### ISSUE THREAD

**Issue by danielvschoor** [UltraMachine/rust-sc2#20]
I get the following error when trying to use `worker.build_gas()`:

```thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', C:\path\rust-sc2\src\unit.rs:1915:18```

When running the code through a debugger, I can see that it happens in this code: 
```
 self.command(
            self.data.game_data.units[&self.data.race_values.gas]
                .ability
                .unwrap(),
            Target::Tag(target),
            queue,
        )```
because `self.data.race_values.gas` is set to `UnitTypeId::NotAUnit`. It seems like every single value in `self.data.race_values` is still set to `UnitTypeId::NotAUnit`, even though it is supposed to be set at runtime.

**Comment by UltraMachine** [comment]
Should be fixed in a683657, check if it works.
