### ISSUE TITLE
failed to select a version for `rust-sc2`

### ISSUE THREAD

**Issue by Xeizzeth** [UltraMachine/rust-sc2#82]
Stumbled upon this error while trying to launch a bot in linux with headful starcraft:  
```
error: failed to select a version for `rust-sc2`.
    ... required by package `rust_sc2_test v0.1.0 (/home/xeizzeth/DATA/Projects/SC2Emul/rust_sc2_test/rust_sc2_test)`
versions that meet the requirements `^1.1.2` (locked to 1.1.2) are: 1.1.2

the package `rust_sc2_test` depends on `rust-sc2`, with features: `wine_sc2` but `rust-sc2` does not have these features.


failed to select a version for `rust-sc2` which could resolve this conflict
```

**Comment by UltraMachine** [comment]
I guess you're using version from crates.io and it's kinda outdated. Try using the one on github.

**Comment by Xeizzeth** [comment]
Believe it or not I did try it. After your suggestion I didn't change anything in the code. And last thing I did is to try to use the github version of the repo.  
But now it works. Amazing...

Please add the hint in the readme, or I'll add it.

**Comment by Xeizzeth** [comment]
@UltraMachine added a pull request https://github.com/UltraMachine/rust-sc2/pull/84
